language: ruby
rvm:
  - 2.1.2
addons:
  code_climate:
    repo_token: 8941b22cf202d2f9948ecb2160433661c3f81893478bb7feaa8637049fc74179
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
